name: Integration continuous

# Déclenche le workflow sur les push et pull requests vers la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Définit les jobs du workflow
jobs:
  frontend-test:
    # Le job est exécuté sur une machine virtuelle Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout le code source
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configuration de Node.js (nécessaire pour Angular)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          yarn install

      # Lancer les tests
      - name: Run tests
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless

