name: Integration continuous

# Déclenche le workflow sur les push et pull requests vers la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Définit les jobs du workflow
jobs:
  frontend-test:
    # Le job est exécuté sur une machine virtuelle Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
      # Checkout le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuration de Node.js (nécessaire pour Angular)
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          yarn install

      # Lancer les tests
      - name: Run tests
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless

